### ISSUE TITLE
你好我们学校是四川天翼飞young3.09

### ISSUE THREAD

**Issue by JONYHY** [EdmondFrank/Esurfing#1]
我想实现路由器里可以自动拨号连接，貌似crazybox里有个拨号协议可以实现 但是找不到源码和编译过程，我也是小白，所以搞不来，看了很多教程貌似没啥用，博主会弄吗？

**Comment by EdmondFrank** [comment]
关于路由器自动登录,我采取的方案是:将登录协议写成shell脚本,再放到一个基于linux内核的路由器上运行.

**Comment by JONYHY** [comment]
谢谢学长的回复，我每次用幻境拨号算出账号可以用来直接用pppoe拨号，我给HG255D刷了openwrt的dreambox系统，你的登陆协议脚本是要改pppd吗？还是自己写的拨号协议算法啊，能否把脚本给我一下，感谢学长的开源精神

**Comment by EdmondFrank** [comment]
留邮箱吧,我们这边是动态获取IP,然后用天翼客户端算法直接登陆的,不用算号.所以可能不适合你们那边使用.

**Comment by JONYHY** [comment]
352144278@qq.com 我们也是动态  我们学校就是天翼飞young客户端

**Comment by EdmondFrank** [comment]
已发,刚才有点事耽搁了..

**Comment by JONYHY** [comment]
太感谢了 ，我学习一下如何使用脚本，再次感谢学长的开源精神

**Comment by MyZiegler** [comment]
博主  有天翼飞5.02破解版本的吗

**Comment by EdmondFrank** [comment]
本项目在16年年底已经放弃维护了，谢谢大家的关注！

**Comment by suda111** [comment]
同天翼飞young，求一下项目文件
