### ISSUE TITLE
路由器登录？

### ISSUE THREAD

**Issue by sexchen** [EdmondFrank/Esurfing#2]
我是广东火炬职院的同学  我们这是用天翼客户端打帐号密码直接登录的  前段时间用的是海洋大学贴吧的软件  后来和谐了  之后自己想了个办法把路由器和手机mac改成一样 能用了 但是好麻烦   博主大大教我怎么路由器登录好吗

**Comment by EdmondFrank** [comment]
本项目已经放弃维护了，本来以为自己发了声明，结果.....没有，不好意思。
除了可以将路由MAC 和 手机Mac 改成一样的方法外，还可以尝试用手机模拟校园网ip，实现欺骗。具体实现方法就见仁见智了！
